global:
  scrape_interval: 15s
scrape_configs:
  - job_name: spring-apps
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["app-01-backend:8080","app-02-backend:8080","app-03-backend:8080","app-04-backend:8080","app-05-backend:8080","app-06-backend:8080","app-07-backend:8080","app-08-backend:8080","app-09-backend:8080","app-10-backend:8080"]
