apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-08-backend
  namespace: java-10-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-08-backend
  template:
    metadata:
      labels:
        app: app-08-backend
    spec:
      containers:
        - name: backend
          image: app-08-backend:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-08-config
            - secretRef:
                name: app-08-secret
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
