CREATE TABLE IF NOT EXISTS users (id BIGSERIAL PRIMARY KEY, email VARCHAR(150) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, role VARCHAR(50) NOT NULL);
CREATE TABLE IF NOT EXISTS posts (id BIGSERIAL PRIMARY KEY, name VARCHAR(255) NOT NULL, status VARCHAR(80) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_posts_name ON posts(name);
